/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI2.java
 *
 * Created on 30/11/2009, 12:34:09
 */
package br.cesupa.CC6TA.GUI.GUI2;

import br.cesupa.CC6TA.Mundo.Jogo.Facade;
import br.cesupa.CC6TA.Mundo.Jogo.Partida;
import br.cesupa.CC6TA.Mundo.Mapa.Mapa;

/**
 *
 * @author root
 */
public class GUI2 extends javax.swing.JFrame {

    Mapa mapa;
    Partida partida;
    Facade fachada;

    /** Creates new form GUI2 */
    public GUI2() {
        super("Mundo de Wumpus");
        initComponents();
        fachada = new Facade();
        partida = fachada.getPartida();
        mapa = partida.getMapa();
        textFieldBuraco1PosicaoX.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBaixo = new javax.swing.JTextArea();
        iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldBuraco2PosicaoX = new javax.swing.JTextField();
        textFieldBuraco3PosicaoX = new javax.swing.JTextField();
        textFieldOuroPosicaoX = new javax.swing.JTextField();
        textFieldWumpusPosicaoX = new javax.swing.JTextField();
        textFieldBuraco1PosicaoX = new javax.swing.JTextField();
        textFieldBuraco1PosicaoY = new javax.swing.JTextField();
        textFieldBuraco2PosicaoY = new javax.swing.JTextField();
        textFieldBuraco3PosicaoY = new javax.swing.JTextField();
        textFieldOuroPosicaoY = new javax.swing.JTextField();
        textFieldWumpusPosicaoY = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDireito = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtEsquerdo = new javax.swing.JTextArea();
        limpar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textFieldPontuacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtBaixo.setColumns(20);
        jtBaixo.setEditable(false);
        jtBaixo.setRows(5);
        jScrollPane1.setViewportView(jtBaixo);

        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buraco1:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ouro:");

        jLabel3.setText("Wumpus:");

        jLabel4.setText("Buraco2:");

        jLabel5.setText("Buraco3:");

        textFieldBuraco1PosicaoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuraco1PosicaoXActionPerformed(evt);
            }
        });

        jLabel6.setText("X");

        jLabel7.setText("Y");

        jtDireito.setColumns(20);
        jtDireito.setEditable(false);
        jtDireito.setRows(5);
        jScrollPane2.setViewportView(jtDireito);

        jtEsquerdo.setColumns(20);
        jtEsquerdo.setEditable(false);
        jtEsquerdo.setRows(5);
        jScrollPane3.setViewportView(jtEsquerdo);

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        jLabel8.setText("Pontuação:");

        textFieldPontuacao.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(limpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciar)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textFieldBuraco1PosicaoX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                            .addComponent(textFieldBuraco2PosicaoX, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldBuraco3PosicaoX, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldBuraco2PosicaoY, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                            .addComponent(textFieldBuraco3PosicaoY, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                            .addComponent(textFieldBuraco1PosicaoY, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(textFieldOuroPosicaoX, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldOuroPosicaoY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(textFieldWumpusPosicaoX, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldWumpusPosicaoY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(73, 73, 73)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textFieldPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(textFieldBuraco1PosicaoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(textFieldBuraco2PosicaoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(textFieldBuraco3PosicaoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldBuraco1PosicaoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldBuraco2PosicaoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldBuraco3PosicaoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textFieldWumpusPosicaoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(textFieldWumpusPosicaoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textFieldOuroPosicaoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldOuroPosicaoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iniciar)
                            .addComponent(limpar)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBuraco1PosicaoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuraco1PosicaoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuraco1PosicaoXActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed

        int buraco1PosicaoX = Integer.parseInt(textFieldBuraco1PosicaoX.getText());
        int buraco1PosicaoY = Integer.parseInt(textFieldBuraco1PosicaoY.getText());

        int buraco2PosicaoX = Integer.parseInt(textFieldBuraco2PosicaoX.getText());
        int buraco2PosicaoY = Integer.parseInt(textFieldBuraco2PosicaoY.getText());

        int buraco3PosicaoX = Integer.parseInt(textFieldBuraco3PosicaoX.getText());
        int buraco3PosicaoY = Integer.parseInt(textFieldBuraco3PosicaoY.getText());

        int ouroPosicaoX = Integer.parseInt(textFieldOuroPosicaoX.getText());
        int ouroPosicaoY = Integer.parseInt(textFieldOuroPosicaoY.getText());

        int wumpusPosicaoX = Integer.parseInt(textFieldWumpusPosicaoX.getText());
        int wumpusPosicaoY = Integer.parseInt(textFieldWumpusPosicaoY.getText());

        fachada.criaBuraco(buraco1PosicaoX, buraco1PosicaoY);
        fachada.criaBuraco(buraco2PosicaoX, buraco2PosicaoY);
        fachada.criaBuraco(buraco3PosicaoX, buraco3PosicaoY);

        fachada.criaWumpus(wumpusPosicaoX, wumpusPosicaoY);

        fachada.criaOuro(ouroPosicaoX, ouroPosicaoY);

        fachada.iniciarPartida();

        preencherTextAreaEsquerdo();
        preencherTextAreaDireito();
        preencherTextAreaBaixo();

        textFieldPontuacao.setText(""+fachada.getAgente().getPontuacao());
    }//GEN-LAST:event_iniciarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        limparTudo();
    }//GEN-LAST:event_limparActionPerformed

    public void preencherTextAreaEsquerdo() {
        for (int i = partida.getMapa().getLinhas() - 1; i >= 0; i--) {
            for (int j = 0; j < partida.getMapa().getColunas(); j++) {
                jtEsquerdo.append("[");

                if (mapa.getMapa()[i][j].isBrisa()) {
                    jtEsquerdo.append("b ");
                }
                if (mapa.getMapa()[i][j].isResplendor()) {
                    jtEsquerdo.append("r ");
                }
                if (mapa.getMapa()[i][j].isFedor()) {
                    jtEsquerdo.append("f ");
                }
                if (mapa.getMapa()[i][j].getObjetoDoTerreno() != null) {
                    jtEsquerdo.append(mapa.getMapa()[i][j].getObjetoDoTerreno().getTipoObjeto().toString());
                }

                jtEsquerdo.append("]\t");
            }
            jtEsquerdo.append("\n");
        }
    }

    public void preencherTextAreaDireito() {


        for (int i = partida.getMapa().getLinhas() - 1; i >= 0; i--) {
            for (int j = 0; j < partida.getMapa().getColunas(); j++) {
                jtDireito.append("[");

                if (mapa.getMapa()[i][j].isPossibilidadeDeBuraco()) {
                    jtDireito.append("pb ");
                }
                if (mapa.getMapa()[i][j].isPossibilidadeDeWumpus()) {
                    jtDireito.append("pw ");
                }
                if (mapa.getMapa()[i][j].isCasaSegura()) {
                    jtDireito.append("OK ");
                }
                if (mapa.getMapa()[i][j].isVisitadoPeloAgente()) {
                    jtDireito.append("V ");
                }
                if (mapa.getMapa()[i][j].getObjetoDoTerreno() != null) {
                    jtDireito.append(mapa.getMapa()[i][j].getObjetoDoTerreno().getTipoObjeto().toString());
                }

                jtDireito.append("]\t");
            }
            jtDireito.append("\n");
        }
    }

    public void preencherTextAreaBaixo() {
        jtBaixo.append(fachada.getAgente().getHistorico().getHistorico());
    }

    public void limparTudo() {
        jtEsquerdo.setText("");
        jtDireito.setText("");
        jtBaixo.setText("");
        textFieldPontuacao.setText("");
        textFieldBuraco1PosicaoX.setText("");
        textFieldBuraco1PosicaoY.setText("");

        textFieldBuraco2PosicaoX.setText("");
        textFieldBuraco2PosicaoY.setText("");

        textFieldBuraco3PosicaoX.setText("");
        textFieldBuraco3PosicaoY.setText("");

        textFieldOuroPosicaoX.setText("");
        textFieldOuroPosicaoY.setText("");

        textFieldWumpusPosicaoX.setText("");
        textFieldWumpusPosicaoY.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jtBaixo;
    private javax.swing.JTextArea jtDireito;
    private javax.swing.JTextArea jtEsquerdo;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField textFieldBuraco1PosicaoX;
    private javax.swing.JTextField textFieldBuraco1PosicaoY;
    private javax.swing.JTextField textFieldBuraco2PosicaoX;
    private javax.swing.JTextField textFieldBuraco2PosicaoY;
    private javax.swing.JTextField textFieldBuraco3PosicaoX;
    private javax.swing.JTextField textFieldBuraco3PosicaoY;
    private javax.swing.JTextField textFieldOuroPosicaoX;
    private javax.swing.JTextField textFieldOuroPosicaoY;
    private javax.swing.JTextField textFieldPontuacao;
    private javax.swing.JTextField textFieldWumpusPosicaoX;
    private javax.swing.JTextField textFieldWumpusPosicaoY;
    // End of variables declaration//GEN-END:variables
}
